# Rules: https://realm.github.io/SwiftLint/rule-directory.html
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - anonymous_argument_in_multiline_closure
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - fatal_error_message
#  - file_types_order # Talvez configurar
  - first_where
  - force_unwrapping
  - indentation_width
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
#  - no_grouping_extension # Caso for separar as extensions em arquivos separados
  - operator_usage_whitespace
#  - prefer_self_in_static_references
  - redundant_type_annotation
  - toggle_bool
  - trailing_closure
#  - type_contents_order # Talvez configurar
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - yoda_condition
  
#disabled_rules: # rule identifiers turned on by default to exclude from running
#  - force_unwrapping
#  - force_cast
#  - force_try
  
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast:
  severity: warning

force_try:
  severity: warning
  
trailing_whitespace:
  ignores_empty_lines: true
  
line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
  warning: 180
  error: 200
    
indentation_width:
  include_comments: false

file_length:
  warning: 500
  error: 1200
  
cyclomatic_complexity:
    warning: 15
    error: 25
  
type_body_length:
  warning: 300
  error: 400

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string
    - completionHandler
    - V
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - to
  allowed_symbols: ["_"]
